import { Bank } from "@models/bank/bank.ts";

/**
 * Regex pattern to validate SWIFT codes.
 * The SWIFT code must follow the format: XXXX XX XX XXX (optional last part for branches).
 * @constant {RegExp}
 */
export const SWIFT_CODE_REGEX = /^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$/;

/**
 * List of all banks in Tanzania with their details.
 * @constant {Bank[]}
 */
export const TZ_BANKS: Bank[] = [
  new Bank("CRDB BANK PLC", "CRDB", "CORUTZTZ"),
  new Bank("PEOPLE'S BANK OF ZANZIBAR LTD", "PBZ", "PBZATZTZ"),
  new Bank("STANDARD CHARTERED BANK (T) LIMITED", "SCB", "SCBLTZTX"),
  new Bank("STANBIC BANK TANZANIA LTD.", "STANBIC", "SBICTZTX"),
  new Bank("CITIBANK TANZANIA LTD", "CITI", "CITITZTZ"),
  new Bank("BANK OF AFRICA TANZANIA LIMITED", "BOA", "EUAFTZTZ"),
  new Bank("DIAMOND TRUST BANK TANZANIA LTD", "DTB", "DTKETZTZ"),
  new Bank("AKIBA COMMERCIAL BANK LTD", "AKIBA", "AKCOTZTZ"),
  new Bank("EXIM BANK (TANZANIA) LTD", "EXIM", "EXTNTZTZ"),
  new Bank("KILIMANJARO CO-OPERATIVE BANK LTD", "KILIMANJARO", "KLMJTZTZ"),
  new Bank("NATIONAL BANK OF COMMERCE LTD", "NBC", "NLCBTZTX"),
  new Bank("NATIONAL MICROFINANCE BANK LIMITED", "NMB", "NMIBTZTZ"),
  new Bank("KCB BANK TANZANIA LIMITED", "KCB", "KCBLTZTZ"),
  new Bank("HABIB AFRICAN BANK LIMITED", "HABIB", "HABLTZTZ"),
  new Bank(
    "INTERNATIONAL COMMERCIAL BANK (TANZANIA) LIMITED",
    "ICB",
    "BKMYTZTZ",
  ),
  new Bank("ABSA BANK TANZANIA LTD", "ABSA", "BARCTZTZ"),
  new Bank("I&M BANK LIMITED", "IMBANK", "IMBLTZTZ"),
  new Bank("NCBA BANK LIMITED", "NCBA", "CBAFTZTZ"),
  new Bank("DAR ES SALAAM COMMUNITY BANK LTD", "DCB", "DASUTZTZ"),
  new Bank("BANK OF BARODA (TANZANIA) LTD", "BARODA", "BARBTZTZ"),
  new Bank("AZANIA BANK LIMITED", "AZANIA", "AZANTZTZ"),
  new Bank("UCHUMI COMMERCIAL BANK (T) LTD", "UCHUMI", "UCCTTZTZ"),
  new Bank(
    "AFRICAN BANKING CORPORATION TANZANIA LIMITED",
    "BANCABC",
    "FMBZTZTX",
  ),
  new Bank("ACCESSBANK TANZANIA LTD", "ACCESS", "ACTZTZTZ"),
  new Bank("BANK OF INDIA (TANZANIA) LIMITED", "BOI", "BKIDTZTZ"),
  new Bank("UNITED BANK FOR AFRICA (T) LTD", "UBA", "UNAFTZTZ"),
  new Bank("MKOMBOZI COMMERCIAL BANK", "MKOMBOZI", "MKCBTZTZ"),
  new Bank("ECOBANK TANZANIA LIMITED", "ECOBANK", "ECOCTZTZ"),
  new Bank("MWANGA HAKIKA MICROFINANCE BANK LIMITED", "MWANGA", "MWCBTZTZ"),
  new Bank("FIRST NATIONAL BANK LIMITED", "FNB", "FIRNTZTX"),
  new Bank("AMANA BANK LIMITED", "AMANA", "AMNNTZTZ"),
  new Bank("EQUITY BANK TANZANIA LIMITED", "EQUITY", "EQBLTZTZ"),
  new Bank("TANZANIA COMMERCIAL BANK PLC", "TCB", "TAPBTZTZ"),
  new Bank("MAENDELEO BANK LTD", "MAENDELEO", "MBTLTZTZ"),
  new Bank("CANARA BANK TANZANIA LTD", "CANARA", "CNRBTZTZ"),
  new Bank("MWALIMU COMMERCIAL BANK PLC", "MWALIMU", "MWCOTZTZ"),
  new Bank("GUARANTY TRUST BANK (T) LTD", "GT BANK", "GTBITZTZ"),
  new Bank("YETU MICROFINANCE BANK PLC", "YETU", "YETMTZTZ"),
  new Bank("CHINA DASHENG BANK LIMITED", "DASHENG", "CDSHTZTZ"),
];
