name: Publish
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: 2.x
    
    - name: Cache dependencies
      run: deno cache mod.ts
    
    - name: Run tests with coverage
      run: deno test

  publish:
    name: Publish to JSR
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish to JSR
        run: deno publish
